FROM python:3.12-slim

WORKDIR /app
COPY proxy/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY proxy /app/proxy

USER 1000:1000
EXPOSE 4000
CMD ["python", "-m", "proxy"]
